language: go
script:
    - go test -v ./... --race --covermode=atomic --coverprofile=profile.cov
after_success:
    - goveralls -coverprofile=profile.cov -service=travis-ci

notifications:
  email: false
